### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by Ghiftee**
- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

Kindly review my PR
Thank you! 😁

### CODE REVIEW

**Review by o-rashad — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Asslam Alikom @Ghiftee  👋😄,
I'm Omar and I will be your reviewer for this project 😊

Good job so far!👌😃, There are some issues 🐞 that you still need to work on to go to the next project but you are almost there! 🏁

## Required Changes ♻️
As expected we need to see an `App` component with routes (from react-router).
- [x] Please adjust your app to have an `App` component
- [x] Make sure that the `App` component has a route that leads to the `Greeting` component.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by o-rashad** [comment]
Hey @Ghiftee, your app is complete.

Sorry for the inconvenient,

Please submit for a new review and it will be accepted immediately.

**Comment by Ghiftee** [comment]
Hello @od-c0d3r ,

My project has all you asked me to add already

**Review by dasileker — APPROVED** [review]
## **Hi @Ghiftee,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
